name: localify
description: Simplify and accelerate localization by effortlessly converting team-sourced data from tools like Google Sheets and Notion into app resource bundles (ARB), making the process easier.
version: 0.0.2
homepage: https://shawnthegreat.dev
repository: https://github.com/shawn-flunge/localify

environment:
  sdk: ^3.0.5

# Add regular dependencies here.
dependencies:
  args: ^2.3.1
  yaml: ^3.1.1
  http: ^1.1.0
  googleapis_auth: ^1.4.1
  googleapis: ^11.3.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
